new branch to realese routeSetup
obox-qr/obox pull request #21
Opened 2024-07-05 14:05 UTC by Zelenro

2024-07-06 08:04 UTC, y-andriievskyi requested changes

2024-07-06 08:04 UTC, y-andriievskyi commented on .env.example
> +DB_CONNECTION_STRING=postgresql://obox_admin:eomkyby1nvXktZC5U7fLlfShLh9S64cA@dpg-cprhs6bqf0us738fmp30-a.frankfurt-postgres.render.com/obox_fpqx?ssl=true
this is sensitive, things like that should never be pushed to repository. store it in your local .env file only

2024-07-06 08:04 UTC, y-andriievskyi commented on ui/package.json
> +    "react-dom": "^18.2.0",
lock versions when you add something. Remove ^ before package version

2024-07-06 08:04 UTC, y-andriievskyi commented on ui/src/layouts/AuthLayout.tsx
> +const AuthLayout =()=>{
Incorrect formatting.
Check MainLayout.tsx

2024-07-06 08:04 UTC, y-andriievskyi commented on ui/src/routes/AuthRoute.tsx
> +const AuthRoute =()=>{
Formatting

2024-07-06 08:04 UTC, y-andriievskyi commented on ui/src/routes/MainRoute.tsx
> +const MainRoute =()=>{
Formatting

2024-07-06 08:04 UTC, y-andriievskyi commented on ui/src/routes/NotFoundRoute.tsx
> +const NotFoundRoute =()=>{
Formatting

2024-07-08 11:04 UTC, Zelenro reviewed
correct commit - clear sensitive information

2024-07-08 11:07 UTC, closed without merging