Bugfix/86bz4fzma
obox-qr/obox pull request #29
Opened 2024-08-01 11:23 UTC by NatalySheludko

Create global styles with Material UI theme, remove styling approach styled-components

2024-08-01 11:26 UTC, y-andriievskyi requested changes

2024-08-01 11:26 UTC, y-andriievskyi commented on ui/src/styles/theme.ts
> +			systemSuccess: '#11BF18',
fix indentation

2024-08-01 11:26 UTC, y-andriievskyi commented on ui/src/styles/theme.types.ts
> +		systemSuccess: string;
indentation

2024-08-01 11:38 UTC, NatalySheludko commented on ui/src/styles/theme.ts
> +			systemSuccess: '#11BF18',
fixed

2024-08-01 11:38 UTC, NatalySheludko commented on ui/src/styles/theme.types.ts
> +		systemSuccess: string;
fixed

2024-08-01 13:15 UTC, y-andriievskyi approved these changes

2024-08-02 18:25 UTC, anastasia1383 approved these changes
Nice

2024-08-03 19:03 UTC, merged